name: CI-CD Pipeline

on:
  push:
    branches: [ main ]          # trigger on main
    tags:
      - 'v*.*.*'                # trigger on semantic tags

permissions:
  contents: write               # needed for release/publishing

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install project + test deps
        run: |
          python -m pip install -U pip
          pip install -e .
          pip install ruff mypy pytest pytest-cov
      - name: Run tests
        run: python -m pytest -q --cov=src --cov-report=term-missing --cov-fail-under=100
      - name: Coverage (HTML + XML)
        run: |
          pytest --cov=src --cov-report=html --cov-report=xml:coverage.xml --cov-fail-under=100
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov

  build:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build sdist + wheel
        run: |
          python -m pip install -U pip build
          python -m build --sdist --wheel
      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  smoke:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Offline install from dist
        run: |
          # replace 'mug' with your importable module name if different
          pip install --no-index --find-links=dist mug-*.whl
      - name: Import + print version
        run: |
          python -c "import mug; print(mug.__version__)"

  deploy:
    needs: [build, smoke]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Validate pyproject.toml version matches tag
        run: |
          TAG_VERSION="${GITHUB_REF##*/}"
          PY_VERSION=$(python -c "import toml; print(toml.load(open('pyproject.toml'))['project']['version'])")
          if [ "v$PY_VERSION" != "$TAG_VERSION" ]; then
            echo "Version mismatch: pyproject.toml ($PY_VERSION) != tag (${TAG_VERSION#v})"
            exit 1
          fi
      - name: Install publish deps
        run: |
          python -m pip install -U pip toml twine
      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*
