name: CI-CD Tag

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install project + test deps (editable)
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install -U pip
          # project + optional test extras (pytest, ruff, mypy, import-linter, pyyaml, etc.)
          python -m pip install -e .[test]
          # ensure tools present even if extras are changed later
          python -m pip install ruff mypy

      - name: ruff (lint)
        shell: bash
        run: |
          set -euo pipefail
          python -m ruff --version
          python -m ruff check --output-format=github .

      - name: mypy (type-check)
        shell: bash
        run: |
          set -euo pipefail
          python -m mypy --version
          python -m mypy --config-file mypy.ini src

      - name: architecture contracts (Import Linter)
        shell: bash
        run: |
          set -euo pipefail
          rm -rf .import_linter_cache || true
          lint-imports --config .importlinter --show-timings

      - name: run tests (use pytest.ini addopts)
        shell: bash
        run: |
          set -euo pipefail
          python -m pytest

      - name: upload html report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov
          if-no-files-found: ignore

  build:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: build sdist + wheel
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install -U pip build
          python -m build --sdist --wheel

      - name: upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  smoke:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: offline install from dist (verify wheel contents first)
        shell: bash
        run: |
          set -euo pipefail
          echo "listing dist/"
          ls -lah dist || true

          # find exactly one wheel (match working style, avoid heredocs)
          WHEEL="$(ls dist/mug-*.whl 2>/dev/null | head -n1 || true)"
          if [[ -z "${WHEEL}" ]]; then
            echo "wheel file not found: dist/mug-*.whl"
            exit 1
          fi
          echo "candidate wheel: ${WHEEL}"

          echo "checking wheel contains 'mug/cli/__init__.py'..."
          if ! unzip -p "${WHEEL}" "mug/cli/__init__.py" >/dev/null 2>&1; then
            echo "ERROR: wheel is missing 'mug/cli/__init__.py'"
            unzip -l "${WHEEL}" || true
            exit 1
          fi

          echo "installing wheel: ${WHEEL}"
          python -m pip install --no-index --no-deps --force-reinstall "${WHEEL}"

          echo "showing wheel contents (non-fatal)"
          unzip -l "${WHEEL}" || true

      - name: smoke test (import + where)
        shell: bash
        run: |
          set -euo pipefail
          python -c $'import importlib\nm=importlib.import_module("mug.cli")\nprint("module file:", getattr(m,"__file__","<no __file__>"))'

  deploy:
    needs: smoke
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: validate pyproject.toml version matches tag
        shell: bash
        run: |
          set -euo pipefail
          TAG_VERSION="${GITHUB_REF##*/}"  # e.g., v0.1.2
          PY_VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])")
          if [[ "v${PY_VERSION}" != "${TAG_VERSION}" ]]; then
            echo "version mismatch: pyproject.toml (${PY_VERSION}) != tag (${TAG_VERSION#v})"
            exit 1
          fi

      - name: install publish deps
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install -U pip twine

      - name: upload to pypi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail
          python -m twine upload dist/*
