name: smoke

on:
  push:
    branches-ignore:
      - main
      - env-test
    tags-ignore:
      - '**'
  pull_request:
    branches-ignore:
      - main
      - env-test
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install test deps
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          python -m pip install -e .[test]

      - name: Pytest smoke
        shell: bash
        run: |
          set -euo pipefail
          # Keep it light; adjust selector as needed
          pytest -q -k "smoke or main_checks or test_repo_basics"
